# Generated by Django 4.2.1 on 2023-05-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('signature', models.CharField(default='keep on rocking', max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
